# Generated by Django 4.2.6 on 2023-12-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_body_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('تکنولوژی', 'تکنولوژی'), ('علمی', 'علمی'), ('سایر', 'سایر')], default='سایر', max_length=20),
        ),
    ]
